# Generated by Django 2.2.2 on 2019-06-27 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='admin', max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('subject', models.CharField(default='Your Contact Query', max_length=100)),
                ('message', models.CharField(max_length=2000)),
                ('sent_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
