# Generated by Django 2.2.2 on 2019-06-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactformmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactformmodel',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
