# Generated by Django 2.2.2 on 2019-06-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20190627_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformmodel',
            name='user',
        ),
    ]
