# Generated by Django 2.2.2 on 2019-06-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190628_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='/static/img/avatars/jenny.jpg', max_length=260),
        ),
    ]
