# Generated by Django 2.2.2 on 2019-06-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20190628_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='/static/img/avatars/sean.png', max_length=260),
        ),
    ]
