# Generated by Django 2.2.2 on 2019-06-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20190630_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='/static/img/avatars/elliot.jpg', max_length=260),
        ),
    ]
