# Generated by Django 2.2.2 on 2019-07-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20190630_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='/static/img/avatars/ade.jpg', max_length=260),
        ),
    ]
