# Generated by Django 2.2.2 on 2019-07-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20190701_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='/static/img/avatars/elliot.jpg', max_length=260),
        ),
    ]
