# Generated by Django 2.2.2 on 2019-07-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20190702_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='/static/img/avatars/ade.jpg', max_length=260),
        ),
    ]
