# Generated by Django 2.2.2 on 2019-07-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20190702_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='/static/img/avatars/violet.jpeg', max_length=260),
        ),
    ]
