# Generated by Django 2.2.2 on 2019-07-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20190702_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='/static/img/avatars/christian.jpg', max_length=260),
        ),
    ]
