# Generated by Django 2.2.2 on 2019-07-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20190705_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='/static/img/avatars/kristy.png', max_length=260),
        ),
    ]
