# Generated by Django 2.2.2 on 2019-07-06 14:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('avatar', models.CharField(blank=True, default='/static/img/avatars/tim.png', max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('status', models.CharField(choices=[('need help', 'need help'), ('in progress', 'in progress'), ('resolved', 'resolved')], default='need help', max_length=100)),
                ('votes', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('earned', models.IntegerField(blank=True, default=0, null=True)),
                ('issue', models.CharField(choices=[('bug', 'bug'), ('feature', 'feature')], max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vote_profiles', models.ManyToManyField(blank=True, related_name='vote_profiles_many', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
