# Generated by Django 2.2.2 on 2019-06-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('need help', 'need help'), ('in progress', 'in progress'), ('resolved', 'resolved')], default='need help', max_length=100),
        ),
    ]
