# Generated by Django 2.2.2 on 2019-06-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
