# Generated by Django 2.2.2 on 2019-07-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
