# Generated by Django 2.2.2 on 2019-06-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20190629_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='earned',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
