# Generated by Django 2.2.2 on 2019-06-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='avatar',
            field=models.CharField(blank=True, default='/static/img/avatars/steve.jpg', max_length=100, null=True),
        ),
    ]
