# Generated by Django 2.2.2 on 2019-06-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20190629_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
