# Generated by Django 2.2.2 on 2019-06-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20190630_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issue',
            field=models.CharField(choices=[('bug', 'bug'), ('feature', 'feature')], default='bug', max_length=100, null=True),
        ),
    ]
