# Generated by Django 2.2.2 on 2019-06-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20190630_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issue',
            field=models.CharField(choices=[('bug', 'bug'), ('feature', 'feature')], max_length=100, null=True),
        ),
    ]
