# Generated by Django 2.2.2 on 2019-07-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20190630_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='avatar',
            field=models.CharField(blank=True, default='/static/img/avatars/tim.png', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
