# Generated by Django 2.2.2 on 2019-07-02 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0010_auto_20190701_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='voted_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='voted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
