# Generated by Django 2.2.2 on 2019-07-02 21:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_ticket_voted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='voted_by',
            field=models.ManyToManyField(blank=True, related_name='voted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
