# Generated by Django 2.2.2 on 2019-07-03 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0012_auto_20190702_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='voted_by',
        ),
        migrations.AddField(
            model_name='ticket',
            name='vote_profiles',
            field=models.ManyToManyField(blank=True, related_name='vote_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
