# Generated by Django 2.2.2 on 2019-07-03 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20190703_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='vote_profiles',
            field=models.ManyToManyField(blank=True, related_name='vote_profiles_many', to=settings.AUTH_USER_MODEL),
        ),
    ]
